source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

project 'FusumaExample.xcodeproj'

target 'FusumaExample' do
  pod 'Fusuma', :path => '../'
end

target 'FusumaUITesting' do
  pod 'Fusuma', :path => '../'
end
